# Generated by Django 4.2.20 on 2025-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=20)),
                ('route_name', models.CharField(max_length=100)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distance_km', models.FloatField()),
                ('time_minutes', models.IntegerField()),
                ('next_bus_in_min', models.IntegerField()),
                ('crowd_level', models.CharField(max_length=20)),
            ],
        ),
    ]
