# Generated by Django 4.2.20 on 2025-04-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=200)),
                ('bus_no', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_time', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_type', models.CharField(max_length=50)),
                ('women_only', models.BooleanField(default=False)),
                ('amenities', models.TextField()),
                ('available_seats', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
